### ISSUE TITLE
is not working with serverless 0.1.0

### ISSUE THREAD

**Issue by krzysu** [Nopik/serverless-serve#11]
I think plugin and documentation should be updated to support latest version of serverless. I'm getting

```
$ sls serve start
/usr/lib/node_modules/serverless/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

TypeError: this.S.validateProject is not a function
    at Serve.serve (/home/kurbas/work/energy-label-generator/node_modules/serverless-serve/index.js:240:21)
```

**Comment by gmittica** [comment]
Same error for me with serverless 0.1.1

**Comment by iblue** [comment]
:+1:

**Comment by iblue** [comment]
To fix this, you can use the version from @benscholler. Go to the root of your project and do

```
npm install benscholler/serverless-serve --save
```

and then add to your `s-project.json`:

```
  "plugins": [
    "serverless-serve"
  ],
```

To start, run `sls serve start`.

**Comment by grandmore** [comment]
In 0.1.2 & 0.1.3 I get a new error:

/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^
TypeError: this.S._init is not a function
    at Serve.serve (/Users/x/lambda/analytics-build/node_modules/serverless-serve/index.js:239:21)

**Comment by krzysu** [comment]
@grandmore should be fixed in 0.1.5

**Comment by madmod** [comment]
:+1:

**Comment by Nopik** [comment]
It should be working now. If this is not the case, please reopen the issue.
